# Generated by Django 4.0.2 on 2022-02-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_address', '0002_address_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='users_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
