# Generated by Django 4.0.2 on 2022-02-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_address', '0004_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='users_address',
        ),
    ]
