# Generated by Django 4.0.2 on 2022-02-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_address', '0003_alter_address_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
